-- 1. 启用地理位置插件 (PostGIS)
-- 这是做地图应用的核心，必须先运行这一句
create extension if not exists postgis;

-- ==========================================
-- 2. 家庭表 (Families) - 数据共享的核心单元
-- ==========================================
create table families (
                          id bigint generated by default as identity primary key,
                          family_name text, -- e.g. "The Li Family"
                          created_at timestamp with time zone default now()
);

-- ==========================================
-- 3. 用户表 (Users/Parents)
-- 关联到 Supabase Auth 和 Family
-- ==========================================
create table user_profiles (
                               id uuid references auth.users primary key, -- 对应 Supabase Auth 的 User ID
                               family_id bigint references families(id), -- 绑定家庭
                               role text check (role in ('admin', 'member')), -- 角色：管理员(妈妈)/成员(爸爸)
                               display_name text,
                               avatar_url text
);

-- ==========================================
-- 4. 孩子档案 (Kids)
-- 用于算法推荐 (比如推荐适合3岁的活动)
-- ==========================================
create table kids (
                      id bigint generated by default as identity primary key,
                      family_id bigint references families(id) not null,
                      nickname text,
                      birth_date date, -- 用于计算实时年龄
                      gender text,
                      preferences jsonb -- 预留字段: e.g. {"likes_dinosaurs": true}
);

-- ==========================================
-- 5. 地点主表 (Places) - 核心资产
-- 无论是公园、餐厅还是 Daycare，都存在这张表里
-- ==========================================
create table places (
                        id bigint generated by default as identity primary key,
                        created_at timestamp with time zone default now(),

                        name text not null,
                        description text,

    -- 地理位置 (经纬度点)
                        location geography(Point) not null,
                        address text,
                        city text,

    -- 核心分类
                        category text not null check (category in ('play_indoor', 'play_outdoor', 'daycare', 'restaurant')),

                        website_url text,
                        google_rating numeric,
                        image_urls text[],  -- 图片数组

    -- 标签系统 (AI 生成)
    -- e.g. ['high_chair', 'splash_pad', 'subsidy_available']
                        tags text[]
);

-- 建立地理位置索引 (让“查找附近”查询飞快)
create index places_geo_index on places using GIST (location);

-- ==========================================
-- 6. Daycare 扩展详情表 (Daycare Details)
-- 只有 category = 'daycare' 的地点才有这部分数据
-- ==========================================
create table daycare_details (
                                 place_id bigint references places(id) primary key,

                                 license_number text,
                                 capacity int,
                                 accepts_infant boolean,
                                 has_subsidy boolean,

    -- 安全记录 (红绿灯)
                                 safety_record text, -- 'Clean', 'Warning'

    -- AI 总结的评价
                                 ai_summary_pros text,
                                 ai_summary_cons text
);

-- ==========================================
-- 7. 活动/事件表 (Events)
-- 有时效性的东西 (CNE, Open House)
-- ==========================================
create table events (
                        id bigint generated by default as identity primary key,
                        place_id bigint references places(id), -- 可选：关联到某个固定地点

                        title text not null,
                        start_date timestamp with time zone not null,
                        end_date timestamp with time zone not null,

                        description text,
                        image_url text,
                        price_info text,
                        is_featured boolean default false -- 是否首页置顶
);

-- ==========================================
-- 8. 收藏与计划 (Saved & Planner)
-- 家庭共享的数据
-- ==========================================
create table saved_items (
                             id bigint generated by default as identity primary key,
                             family_id bigint references families(id), -- 整个家庭可见

                             place_id bigint references places(id),
                             event_id bigint references events(id),

    -- 列表类型
                             list_type text check (list_type in ('wishlist', 'planned', 'visited', 'daycare_watch')),

    -- 计划日期 (如果是 'planned')
                             planned_date timestamp with time zone,

    -- Daycare CRM 状态笔记
                             notes text
);