-- Enable PostGIS for geolocation features
create extension if not exists postgis;

-- 1. FAMILIES (The core unit for data sharing)
create table families (
  id bigint generated by default as identity primary key,
  family_name text, 
  created_at timestamp default now()
);

-- 2. USERS (Parents)
create table user_profiles (
  id uuid references auth.users primary key,
  family_id bigint references families(id), -- Links to the family unit
  role text check (role in ('admin', 'member')), 
  display_name text,
  avatar_url text
);

-- 3. KIDS (For algorithm personalization)
create table kids (
  id bigint generated by default as identity primary key,
  family_id bigint references families(id) not null,
  nickname text,
  birth_date date, -- Used to calculate age dynamically
  gender text,
  preferences jsonb -- e.g. {"likes_dinosaurs": true}
);

-- 4. PLACES (Base table for Play, Eat, and Learn)
create table places (
  id bigint generated by default as identity primary key,
  name text not null, 
  description text,   
  location geography(Point) not null, -- PostGIS point
  address text,
  city text,          
  category text not null check (category in ('play_indoor', 'play_outdoor', 'daycare', 'restaurant')),
  website_url text,
  google_rating numeric,     
  image_urls text[],  
  tags text[] -- AI generated tags: ['high_chair', 'splash_pad']
);

-- Index for fast geo-searches
create index places_geo_index on places using GIST (location);

-- 5. DAYCARE DETAILS (Extended table for 'Learn')
create table daycare_details (
  place_id bigint references places(id) primary key,
  license_number text,      
  capacity int,             
  accepts_infant boolean,   
  has_subsidy boolean,      
  safety_record text, -- 'Clean', 'Warning'
  ai_summary_pros text,     
  ai_summary_cons text      
);

-- 6. EVENTS (Seasonal/Temporary items)
create table events (
  id bigint generated by default as identity primary key,
  place_id bigint references places(id), -- Optional link to a place
  title text not null,
  start_date timestamp with time zone not null,
  end_date timestamp with time zone not null,
  description text,
  image_url text,
  price_info text, 
  is_featured boolean default false 
);

-- 7. FAVORITES & PLANNER
create table saved_items (
  id bigint generated by default as identity primary key,
  family_id bigint references families(id), -- Shared across family
  place_id bigint references places(id),
  event_id bigint references events(id),
  list_type text check (list_type in ('wishlist', 'planned', 'visited')),
  planned_date timestamp with time zone, -- If set, shows in "Upcoming"
  notes text
);
